dist: trusty
sudo: false
language: ruby
rvm:
  - 2.4
  - 2.3
  - 2.2
  - 2.1
  # Using exact version as workaround for https://github.com/travis-ci/travis-ci/issues/8446.
  - jruby-9.1.15.0
  - ruby-head
  - jruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
env:
  global:
    secure: # CODACY_PROJECT_TOKEN
script:
  - bundle exec rake spec
  - bundle exec rake rubocop
deploy:
  provider: rubygems
  api_key:
    secure: <RUBYGEMS KEY>
  on:
    rvm: 2.4
    tags: true
